In [3]:
import pandas as pd
df = pd.read_csv("Tab.csv")

In [4]:
for i in df.index:
    print("Negara {}".format(df['Negara']))
    print("Populasi {}".format(df['Populasi']))
    print("Area {}".format(df['Area']))
    print("Ibu Kota {}".format(df['Ibukota']))

Negara 0    Indonesia
1     Malaysia
2    Singapura
3       Jepang
4     Thailand
Name: Negara, dtype: object
Populasi 0    250
1     25
2     15
3     60
4     45
Name: Populasi, dtype: int64
Area 0    123456
1      3456
2       456
3      5678
4       678
Name: Area, dtype: int64
Ibu Kota 0      Jakarta
1           KL
2    Singapura
3        Tokyo
4      Bangkok
Name: Ibukota, dtype: object
Negara 0    Indonesia
1     Malaysia
2    Singapura
3       Jepang
4     Thailand
Name: Negara, dtype: object
Populasi 0    250
1     25
2     15
3     60
4     45
Name: Populasi, dtype: int64
Area 0    123456
1      3456
2       456
3      5678
4       678
Name: Area, dtype: int64
Ibu Kota 0      Jakarta
1           KL
2    Singapura
3        Tokyo
4      Bangkok
Name: Ibukota, dtype: object
Negara 0    Indonesia
1     Malaysia
2    Singapura
3       Jepang
4     Thailand
Name: Negara, dtype: object
Populasi 0    250
1     25
2     15
3     60
4     45
Name: Populasi, dtype: int64
Area 0    123456
1      3456
2       456
3      5678
4       678
Name: Area, dtype: int64
Ibu Kota 0      Jakarta
1           KL
2    Singapura
3        Tokyo
4      Bangkok
Name: Ibukota, dtype: object
Negara 0    Indonesia
1     Malaysia
2    Singapura
3       Jepang
4     Thailand
Name: Negara, dtype: object
Populasi 0    250
1     25
2     15
3     60
4     45
Name: Populasi, dtype: int64
Area 0    123456
1      3456
2       456
3      5678
4       678
Name: Area, dtype: int64
Ibu Kota 0      Jakarta
1           KL
2    Singapura
3        Tokyo
4      Bangkok
Name: Ibukota, dtype: object
Negara 0    Indonesia
1     Malaysia
2    Singapura
3       Jepang
4     Thailand
Name: Negara, dtype: object
Populasi 0    250
1     25
2     15
3     60
4     45
Name: Populasi, dtype: int64
Area 0    123456
1      3456
2       456
3      5678
4       678
Name: Area, dtype: int64
Ibu Kota 0      Jakarta
1           KL
2    Singapura
3        Tokyo
4      Bangkok
Name: Ibukota, dtype: object